function report = test_scenario()
%TEST_SCENARIO Run the full 5-task, 3-AGV scenario and report metrics.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(projectRoot);

config = params();
config.enableVisualization = false;
config.visualizerVisible = false;
config.dt = 1.0;
config.totalTime = 260.0;
config.dynamicObstacleSchedule = struct( ...
    'startTime', 0.0, ...
    'endTime', 3.0, ...
    'positions', [1, 24]);

simulation = sim.Simulation.fromDefaults(config);
results = simulation.run();
report = buildScenarioReport(results);

assert(report.completedTaskCount == 5, 'All five tasks should complete in the scenario test.');
assert(report.collisionCount == 0, 'Scenario should not contain collisions.');
assert(report.avoidanceCount >= 1, 'Scenario should trigger at least one dynamic avoidance event.');
assert(numel(report.taskCompletionTimes) == 5, 'Scenario report should include all task completion times.');
assert(numel(report.agvDistances) == 3, 'Scenario report should include all AGV travel distances.');
assert(all(strcmp({simulation.taskList.status}, 'completed')), 'All tasks should finish with completed status.');
assert(sim.Simulation.countEvents(results.eventLog, 'task_assigned') == 5, ...
    'All five tasks should be assigned during the scenario.');

disp('Scenario report:');
disp(struct( ...
    'totalTime', report.totalTime, ...
    'completedTaskCount', report.completedTaskCount, ...
    'collisionCount', report.collisionCount, ...
    'conflictResolutionCount', report.conflictResolutionCount, ...
    'replanCount', report.replanCount, ...
    'avoidanceCount', report.avoidanceCount, ...
    'taskAssignmentFailureCount', report.taskAssignmentFailureCount));
disp('AGV distances:');
disp(struct2table(report.agvDistances));
disp('Task completion times:');
disp(struct2table(report.taskCompletionTimes));

disp('test_scenario passed');
end

function report = buildScenarioReport(results)
metrics = results.metrics;
report = struct( ...
    'totalTime', metrics.totalTime, ...
    'completedTaskCount', metrics.completedTaskCount, ...
    'collisionCount', metrics.collisionCount, ...
    'conflictResolutionCount', metrics.conflictResolutionCount, ...
    'replanCount', metrics.replanCount, ...
    'avoidanceCount', metrics.avoidanceCount, ...
    'taskAssignmentFailureCount', metrics.taskAssignmentFailureCount, ...
    'agvDistances', metrics.agvDistances, ...
    'taskCompletionTimes', metrics.taskCompletionTimes);
end
