function test_timewindow()
%TEST_TIMEWINDOW Validate time window reservation and conflict detection.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(projectRoot);

manager = timewindow.TimeWindowManager();

windowA = manager.addTimeWindow([3, 3, 3, 4], 0.0, 1.0, 1, 0);
[hasConflict, info] = manager.detectConflict(struct( ...
    'edgeIndex', [3, 3, 3, 4], ...
    'startTime', 0.5, ...
    'endTime', 1.5, ...
    'agvId', 2, ...
    'direction', 0));
assert(hasConflict, 'Overlapping use of the same edge should conflict.');
assert(strcmp(info.type, 'same_direction_overlap'), 'Conflict type should mark same-direction overlap.');
assert(windowA.agvId == 1, 'Added window should preserve AGV id.');

[hasConflict, info] = manager.detectConflict(struct( ...
    'edgeIndex', [3, 4, 3, 3], ...
    'startTime', 0.25, ...
    'endTime', 0.75, ...
    'agvId', 3, ...
    'direction', 2));
assert(hasConflict, 'Opposite-direction use of the same edge should conflict.');
assert(strcmp(info.type, 'opposite_direction_overlap'), ...
    'Conflict type should mark opposite-direction overlap.');

[reservedWindows, conflictInfo] = manager.reservePath(4, [1, 1; 1, 2; 1, 3], 2.0, 1.0);
assert(isempty(conflictInfo), 'Conflict info should be empty when reservation succeeds.');
assert(numel(reservedWindows) == 2, 'Path reservation should create one window per edge.');
assert(abs(reservedWindows(1).startTime - 2.0) < 1e-9 && abs(reservedWindows(1).endTime - 3.0) < 1e-9, ...
    'First reserved edge timing is incorrect.');
assert(abs(reservedWindows(2).startTime - 3.0) < 1e-9 && abs(reservedWindows(2).endTime - 4.0) < 1e-9, ...
    'Second reserved edge timing is incorrect.');

[reservedWindowsBlocked, conflictInfo] = manager.reservePath(5, [1, 3; 1, 2], 3.2, 1.0);
assert(isempty(reservedWindowsBlocked), 'Conflicting path should not be reserved.');
assert(~isempty(conflictInfo), 'Conflict details should be returned when reservation fails.');
assert(strcmp(conflictInfo.type, 'opposite_direction_overlap'), ...
    'Reverse use of the reserved edge should be reported as opposite-direction overlap.');

[hasConflict, ~] = manager.detectConflict(struct( ...
    'edgeIndex', [5, 5, 5, 6], ...
    'startTime', 10.0, ...
    'endTime', 11.0, ...
    'agvId', 6, ...
    'direction', 0));
assert(~hasConflict, 'Independent edge usage should not conflict.');

manager.releasePath(4, [1, 1; 1, 2; 1, 3]);
remainingAgvIds = [manager.timeWindows.agvId];
assert(~any(remainingAgvIds == 4), 'Released path windows should be removed from the manager.');
assert(any(remainingAgvIds == 1), 'Unrelated reservations should remain after releasing a path.');

manager.releasePath(1);
assert(isempty(manager.timeWindows), 'Releasing an AGV without a path should remove all of its windows.');

disp('test_timewindow passed');
end
