function report = test_scenario()
%TEST_SCENARIO Run the full 30-task, 10-AGV input scenario and report metrics.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(projectRoot);

config = params();
config.enableVisualization = false;
config.visualizerVisible = false;
config.dt = 1.0;
config.totalTime = 4200.0;
config.dynamicObstacleSchedule = repmat(struct( ...
    'startTime', 0.0, ...
    'endTime', 0.0, ...
    'positions', zeros(0, 2)), 0, 1);

simulation = sim.Simulation.fromDefaults(config);
results = simulation.run();
report = buildScenarioReport(results);

assert(numel(simulation.agvPool) == 10, 'Scenario should load ten AGVs from input/agv_pool.json.');
assert(numel(simulation.taskList) == 30, 'Scenario should load thirty tasks from input/task_list.json.');
assert(report.completedTaskCount == 30, 'All thirty tasks should complete in the scenario test.');
assert(report.collisionCount == 0, 'Scenario should not contain collisions.');
assert(numel(report.taskCompletionTimes) == 30, 'Scenario report should include all task completion times.');
assert(numel(report.agvDistances) == 10, 'Scenario report should include all AGV travel distances.');
assert(all(strcmp({simulation.taskList.status}, 'completed')), 'All tasks should finish with completed status.');
assert(sim.Simulation.countEvents(results.eventLog, 'task_assigned') == 30, ...
    'All thirty tasks should be assigned during the scenario.');
assert(sim.Simulation.countEvents(results.eventLog, 'parking_return_completed') >= 1, ...
    'Scenario should log AGV return-to-parking completion.');
finalPositions = reshape([simulation.agvPool.position], 2, []).';
inputAgvPool = agv.AGVClass.loadPool(fullfile(projectRoot, 'input', 'agv_pool.json'));
expectedParking = reshape([inputAgvPool.position], 2, []).';
assert(isequal(round(finalPositions), expectedParking), ...
    'All AGVs should return to their input parking positions after the scenario.');

disp('Scenario report:');
disp(struct( ...
    'totalTime', report.totalTime, ...
    'completedTaskCount', report.completedTaskCount, ...
    'collisionCount', report.collisionCount, ...
    'conflictResolutionCount', report.conflictResolutionCount, ...
    'replanCount', report.replanCount, ...
    'avoidanceCount', report.avoidanceCount, ...
    'taskAssignmentFailureCount', report.taskAssignmentFailureCount));
disp('AGV distances:');
disp(struct2table(report.agvDistances));
disp('Task completion times:');
disp(struct2table(report.taskCompletionTimes));

disp('test_scenario passed');
end

function report = buildScenarioReport(results)
metrics = results.metrics;
report = struct( ...
    'totalTime', metrics.totalTime, ...
    'completedTaskCount', metrics.completedTaskCount, ...
    'collisionCount', metrics.collisionCount, ...
    'conflictResolutionCount', metrics.conflictResolutionCount, ...
    'replanCount', metrics.replanCount, ...
    'avoidanceCount', metrics.avoidanceCount, ...
    'taskAssignmentFailureCount', metrics.taskAssignmentFailureCount, ...
    'agvDistances', metrics.agvDistances, ...
    'taskCompletionTimes', metrics.taskCompletionTimes);
end
